### ISSUE TITLE
indentation error

### ISSUE THREAD

**Issue by casens5** [oakmac/standard-clojure-style-js#157]
i'm using `v0.14.0`.  it seems that standard-clj corrects
```
(+ (+ 3 5)
(- 4 5))
```
or
```
(+ (+ 3 5)
        (- 4 5))
```
to
```
(+ (+ 3 5)
  (- 4 5))
```
where i would expect
```
(+ (+ 3 5)
   (- 4 5))
```

**Comment by oakmac** [comment]
This is a question of [of "Rule 3" alignment](https://github.com/clj-commons/formatter/issues/9#issuecomment-446167649).

If you want the nested form `(- 4 5)` to be vertically aligned under `(+ 3 5)`, then provide the following to Standard Clojure Style:

```clj
(+ (+ 3 5)
   (- 4 5))
```

Otherwise you will get Fixed Indentation (ie: two spaces) as in your examples.
