### ISSUE TITLE
ability to ignore the next form

### ISSUE THREAD

**Issue by oakmac** [oakmac/standard-clojure-style-js#6]
Users should have a simple way to tell the formatter "ignore the next form".

Current idea: comments that contain the string `clojurefmt:ignore` will cause the next form to be ignored.

I want to avoid using metadata for this purpose because I do not want to create the impression that this can be adjusted at runtime programmatically.

**Comment by NoahTheDuke** [comment]
Prior art:

* clj-kondo uses `#_` before any form, which you linked above.
* Splint (my linter) uses `#_` before any form: https://cljdoc.org/d/io.github.noahtheduke/splint/1.15.2/doc/configuration#disabling-rules-inline
* zprint uses `;!zprint` at column 1 of a line: https://github.com/kkinnear/zprint/blob/main/doc/bang.md
* cljstyle uses `^:cljstyle/ignore` metadata: https://github.com/greglook/cljstyle?tab=readme-ov-file#ignoring-forms
* I don't think weavejester's cljfmt has any way to ignore a form, given this issue is still open: https://github.com/weavejester/cljfmt/issues/78

**Comment by oakmac** [comment]
I am leaning toward something very similar to [how clj-kondo works](https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#ignore-warnings-in-an-expression):

#### Ignore the next form

* `#_:standard-clj/ignore` - ignores the next form
* `#_{:standard-clj/ignore true}` - same as above
* Should we only support this for "top-level" forms?

#### Ignore the whole file

* `#_:standard-clj/ignore-file` - ignores the whole file, must be placed at the top of the file
* `#_{:standard-clj/ignore-file true}` - same as above

**Comment by oakmac** [comment]
[PR-120](https://github.com/oakmac/standard-clojure-style-js/pull/120) adds support for `#_:standard-clj/ignore` and `#_{:standard-clj/ignore true}`

Next up is adding support for `#_ :standard-clj/ignore-file`

**Comment by oakmac** [comment]
[PR-122](https://github.com/oakmac/standard-clojure-style-js/pull/122) adds support for `#_ :standard-clj/ignore-file`
